
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.1.0"

[[constraint]]
  version = "v0.1.1"
  name = "github.com/oilbeater/libovsdb"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/cenkalti/hub"
  revision = "11382a9960d39b0ecda16fd01c424c11ff765a34"

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/rpc2"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "v0.6.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "v0.2.15"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"
