kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.18.0
  - role: control-plane
    image: kindest/node:v1.18.0
  - role: control-plane
    image: kindest/node:v1.18.0
