kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: true
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "feature-gates": "SCTPSupport=true"
    etcd:
      local:
        dataDir: "/tmp/lib/etcd"
nodes:
  - role: control-plane
    image: kindest/node:v1.18.2
  - role: worker
    image: kindest/node:v1.18.2
