kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: ipvs
  disableDefaultCNI: true
  ipFamily: ipv4

kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "feature-gates": "SCTPSupport=true"
    etcd:
      local:
        dataDir: "/tmp/lib/etcd"
nodes:
  - role: control-plane
    image: kindest/node:v1.19.1
  - role: worker
    image: kindest/node:v1.19.1
