name: Build x86 Image

on:
  push:
    branches:
    - master
    - feat/github-action
    paths-ignore:
    - 'docs/**'
    - 'dist/**'
    - 'yamls/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0
      - name: Build
        run: make release
      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALAUDA_USERNAME: ${{ secrets.ALAUDA_USERNAME }}
          ALAUDA_PASSWORD: ${{ secrets.ALAUDA_PASSWORD }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag index.alauda.cn/alaudak8s/kube-ovn:$TAG kubeovn/kube-ovn:$TAG
          docker images
          docker push kubeovn/kube-ovn:$TAG
